<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <RootNamespace>Regira.Fleet.Models</RootNamespace>
      <AssemblyName>Regira.Fleet.Models</AssemblyName>
      <Authors>B.Verboven</Authors>
      <Company>Regira</Company>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Regira.Entities" Version="5.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fleet.Core\Fleet.Core.csproj" />
  </ItemGroup>

</Project>
