<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>Regira.Fleet.Data.PostgreSQL</RootNamespace>
        <AssemblyName>Regira.Fleet.Data.PostgreSQL</AssemblyName>
        <Authors>B.Verboven</Authors>
        <Company>Regira</Company>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fleet.Data.Core\Fleet.Data.Core.csproj" />
        <PackageReference Include="EFCore.NamingConventions" Version="8.0.3" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.2" />
    </ItemGroup>

</Project>
