<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>Regira.Fleet.Data.MySQL</RootNamespace>
        <AssemblyName>Regira.Fleet.Data.MySQL</AssemblyName>
        <Authors>B.Verboven</Authors>
        <Company>Regira</Company>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fleet.Data.Core\Fleet.Data.Core.csproj" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.8" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    </ItemGroup>

</Project>
