<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<RootNamespace>Regira.Fleet.Data.MySQL</RootNamespace>
	<AssemblyName>Regira.Fleet.Data.MySQL</AssemblyName>
	<Authors>B.Verboven</Authors>
	<Company>Regira</Company>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\Fleet.Data.Core\Fleet.Data.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
	<PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.9" />
  </ItemGroup>

</Project>
