<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>bbdb45a3-5938-4049-af56-7790fb6bd144</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.3" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.3" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.3" />
        <PackageReference Include="Regira.Security" Version="4.3.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fleet.Data.MySQL\Fleet.Data.MySQL.csproj" />
        <ProjectReference Include="..\Fleet.Data.PostgreSQL\Fleet.Data.PostgreSQL.csproj" />
        <ProjectReference Include="..\Fleet.Data.SqlServer\Fleet.Data.SqlServer.csproj" />
        <ProjectReference Include="..\Fleet.Identity.Data.MySQL\Fleet.Identity.Data.MySQL.csproj" />
        <ProjectReference Include="..\Fleet.Identity.Data.PostgreSQL\Fleet.Identity.Data.PostgreSQL.csproj" />
        <ProjectReference Include="..\Fleet.Identity.Data.SqlServer\Fleet.Identity.Data.SqlServer.csproj" />
        <ProjectReference Include="..\Fleet.Identity\Fleet.Identity.csproj" />
        <ProjectReference Include="..\Fleet.Library\Fleet.Library.csproj" />
    </ItemGroup>

</Project>