<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>Regira.Fleet</RootNamespace>
        <AssemblyName>Regira.Fleet</AssemblyName>
        <Authors>B.Verboven</Authors>
        <Company>Regira</Company>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="13.0.1" />
        <PackageReference Include="Dapper" Version="2.1.66" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Regira.Globalization.LibPhoneNumber" Version="4.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fleet.Core\Fleet.Core.csproj" />
        <ProjectReference Include="..\Fleet.Data.Core\Fleet.Data.Core.csproj" />
        <ProjectReference Include="..\Fleet.Models\Fleet.Models.csproj" />
    </ItemGroup>

</Project>
