<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Regira.Fleet.Identity</RootNamespace>
        <AssemblyName>Regira.Fleet.Identity</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="13.0.1" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Regira.Common" Version="4.0.8" />
        <PackageReference Include="Regira.Office" Version="4.0.9" />
        <PackageReference Include="Regira.Entities.DependencyInjection" Version="4.0.11" />
        <PackageReference Include="Regira.Security.Authentication" Version="4.0.9" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fleet.Core\Fleet.Core.csproj" />
        <ProjectReference Include="..\Fleet.Identity.Data.Core\Fleet.Identity.Data.Core.csproj" />
        <ProjectReference Include="..\Fleet.Identity.Models\Fleet.Identity.Models.csproj" />
    </ItemGroup>

</Project>
