<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Regira.Fleet.Identity</RootNamespace>
        <AssemblyName>Regira.Fleet.Identity</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="13.0.1" />
        <PackageReference Include="EFCore.NamingConventions" Version="8.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.2" />
        <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.2" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.2" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Regira.Common" Version="4.0.3" />
        <PackageReference Include="Regira.Office" Version="4.0.5" />
        <PackageReference Include="Regira.Entities.DependencyInjection" Version="4.0.5" />
        <PackageReference Include="Regira.Security.Authentication" Version="4.0.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fleet.Core\Fleet.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations\" />
    </ItemGroup>

</Project>
