// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Regira.Fleet.Identity.Data.PostgreSQL;

#nullable disable

namespace Regira.Fleet.Identity.Migrations;

[DbContext(typeof(AccountsPostgresContext))]
partial class AccountsContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("id");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("text")
                    .HasColumnName("concurrency_stamp");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("name");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_name");

                b.HasKey("Id")
                    .HasName("pk_asp_net_roles");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex");

                b.ToTable("AspNetRoles", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("text")
                    .HasColumnName("claim_type");

                b.Property<string>("ClaimValue")
                    .HasColumnType("text")
                    .HasColumnName("claim_value");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("character varying(64)")
                    .HasColumnName("role_id");

                b.HasKey("Id")
                    .HasName("pk_asp_net_role_claims");

                b.HasIndex("RoleId")
                    .HasDatabaseName("ix_asp_net_role_claims_role_id");

                b.ToTable("AspNetRoleClaims", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("claim_type");

                b.Property<string>("ClaimValue")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("claim_value");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("character varying(64)")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_asp_net_user_claims");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_asp_net_user_claims_user_id");

                b.ToTable("AspNetUserClaims", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("login_provider");

                b.Property<string>("ProviderKey")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("provider_key");

                b.Property<string>("ProviderDisplayName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("provider_display_name");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("user_id");

                b.HasKey("LoginProvider", "ProviderKey")
                    .HasName("pk_asp_net_user_logins");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_asp_net_user_logins_user_id");

                b.ToTable("AspNetUserLogins", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("user_id");

                b.Property<string>("RoleId")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("role_id");

                b.HasKey("UserId", "RoleId")
                    .HasName("pk_asp_net_user_roles");

                b.HasIndex("RoleId")
                    .HasDatabaseName("ix_asp_net_user_roles_role_id");

                b.ToTable("AspNetUserRoles", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("user_id");

                b.Property<string>("LoginProvider")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("login_provider");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("name");

                b.Property<string>("Value")
                    .HasColumnType("text")
                    .HasColumnName("value");

                b.HasKey("UserId", "LoginProvider", "Name")
                    .HasName("pk_asp_net_user_tokens");

                b.ToTable("AspNetUserTokens", (string)null);
            });

        modelBuilder.Entity("Regira.Fleet.Identity.Entities.Clients.Client", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("id");

                b.Property<string>("Code")
                    .HasMaxLength(8)
                    .HasColumnType("character varying(8)")
                    .HasColumnName("code");

                b.Property<DateTime>("Created")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("created");

                b.Property<string>("DefaultCulture")
                    .HasMaxLength(8)
                    .HasColumnType("character varying(8)")
                    .HasColumnName("default_culture");

                b.Property<string>("Description")
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<DateTime?>("LastModified")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("last_modified");

                b.Property<string>("NormalizedTitle")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_title");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("title");

                b.HasKey("Id")
                    .HasName("pk_clients");

                b.ToTable("clients", (string)null);
            });

        modelBuilder.Entity("Regira.Fleet.Identity.Entities.Clients.ClientLanguage", b =>
            {
                b.Property<string>("ClientId")
                    .HasColumnType("character varying(32)")
                    .HasColumnName("client_id");

                b.Property<string>("LangCode")
                    .HasMaxLength(2)
                    .HasColumnType("character varying(2)")
                    .HasColumnName("lang_code");

                b.HasKey("ClientId", "LangCode")
                    .HasName("pk_client_languages");

                b.ToTable("client_languages", (string)null);
            });

        modelBuilder.Entity("Regira.Fleet.Identity.Entities.Clients.Subscriptions.ClientSubscription", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClientId")
                    .IsRequired()
                    .HasColumnType("character varying(32)")
                    .HasColumnName("client_id");

                b.Property<DateTime>("Created")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("created");

                b.Property<string>("Description")
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<DateTime?>("EndDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("end_date");

                b.Property<DateTime?>("LastModified")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("last_modified");

                b.Property<DateTime?>("StartDate")
                    .IsRequired()
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("start_date");

                b.HasKey("Id")
                    .HasName("pk_client_subscriptions");

                b.HasIndex("ClientId")
                    .HasDatabaseName("ix_client_subscriptions_client_id");

                b.ToTable("client_subscriptions", (string)null);
            });

        modelBuilder.Entity("Regira.Fleet.Identity.Entities.Users.Claims.ClientUserClaim", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("claim_type");

                b.Property<string>("ClaimValue")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("claim_value");

                b.Property<string>("ClientId")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("client_id");

                b.Property<DateTime>("Created")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("created");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_client_user_claims");

                b.HasIndex("ClientId")
                    .HasDatabaseName("ix_client_user_claims_client_id");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_client_user_claims_user_id");

                b.HasIndex("ClientId", "UserId", "ClaimType", "ClaimValue")
                    .IsUnique()
                    .HasDatabaseName("ix_client_user_claims_client_id_user_id_claim_type_claim_value");

                b.ToTable("client_user_claims", (string)null);
            });

        modelBuilder.Entity("Regira.Fleet.Identity.Entities.Users.FleetUser", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("id");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("integer")
                    .HasColumnName("access_failed_count");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("concurrency_stamp");

                b.Property<string>("Culture")
                    .HasMaxLength(8)
                    .HasColumnType("character varying(8)")
                    .HasColumnName("culture");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("email");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("boolean")
                    .HasColumnName("email_confirmed");

                b.Property<string>("GivenName")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("given_name");

                b.Property<string>("LastName")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("last_name");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("boolean")
                    .HasColumnName("lockout_enabled");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("lockout_end");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_email");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_user_name");

                b.Property<string>("PasswordHash")
                    .HasMaxLength(2048)
                    .HasColumnType("character varying(2048)")
                    .HasColumnName("password_hash");

                b.Property<string>("PhoneNumber")
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("phone_number");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("boolean")
                    .HasColumnName("phone_number_confirmed");

                b.Property<string>("SecurityStamp")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("security_stamp");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("boolean")
                    .HasColumnName("two_factor_enabled");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("user_name");

                b.HasKey("Id")
                    .HasName("pk_asp_net_users");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex");

                b.ToTable("AspNetUsers", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("Regira.Fleet.Identity.Entities.Users.FleetUser", null)
                    .WithMany("UserClaims")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("Regira.Fleet.Identity.Entities.Users.FleetUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                b.HasOne("Regira.Fleet.Identity.Entities.Users.FleetUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("Regira.Fleet.Identity.Entities.Users.FleetUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
            });

        modelBuilder.Entity("Regira.Fleet.Identity.Entities.Clients.ClientLanguage", b =>
            {
                b.HasOne("Regira.Fleet.Identity.Entities.Clients.Client", null)
                    .WithMany("Languages")
                    .HasForeignKey("ClientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_client_languages_clients_client_id");
            });

        modelBuilder.Entity("Regira.Fleet.Identity.Entities.Clients.Subscriptions.ClientSubscription", b =>
            {
                b.HasOne("Regira.Fleet.Identity.Entities.Clients.Client", "Client")
                    .WithMany("Subscriptions")
                    .HasForeignKey("ClientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_client_subscriptions_clients_client_id");

                b.Navigation("Client");
            });

        modelBuilder.Entity("Regira.Fleet.Identity.Entities.Users.Claims.ClientUserClaim", b =>
            {
                b.HasOne("Regira.Fleet.Identity.Entities.Clients.Client", "Client")
                    .WithMany("UserClaims")
                    .HasForeignKey("ClientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_client_user_claims_clients_client_id");

                b.HasOne("Regira.Fleet.Identity.Entities.Users.FleetUser", "User")
                    .WithMany("ClientClaims")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_client_user_claims_users_user_id");

                b.Navigation("Client");

                b.Navigation("User");
            });

        modelBuilder.Entity("Regira.Fleet.Identity.Entities.Clients.Client", b =>
            {
                b.Navigation("Languages");

                b.Navigation("Subscriptions");

                b.Navigation("UserClaims");
            });

        modelBuilder.Entity("Regira.Fleet.Identity.Entities.Users.FleetUser", b =>
            {
                b.Navigation("ClientClaims");

                b.Navigation("UserClaims");
            });
#pragma warning restore 612, 618
    }
}
