<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Regira.Fleet.Core</RootNamespace>
        <AssemblyName>Regira.Fleet.Core</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Regira.Entities.DependencyInjection" Version="4.2.8" />
    </ItemGroup>

</Project>
