<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Regira.Fleet.Core</RootNamespace>
        <AssemblyName>Regira.Fleet.Core</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Regira.Entities.DependencyInjection" Version="4.0.6" />
    </ItemGroup>

</Project>
