<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Regira.Fleet.Identity.Web</RootNamespace>
        <AssemblyName>Regira.Fleet.Identity.Web</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Regira.Entities.Web" Version="6.0.0" />
        <PackageReference Include="Regira.Office" Version="6.0.0" />
        <PackageReference Include="Regira.Security" Version="6.0.0" />
        <PackageReference Include="Regira.Security.Authentication.Web" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Fleet.Identity.DependencyInjection\Fleet.Identity.DependencyInjection.csproj" />
      <ProjectReference Include="..\Fleet.Identity.Models\Fleet.Identity.Models.csproj" />
      <ProjectReference Include="..\Fleet.Identity\Fleet.Identity.csproj" />
    </ItemGroup>

</Project>
