<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>Regira.Fleet.Identity.Data</RootNamespace>
        <AssemblyName>Regira.Fleet.Identity.Data</AssemblyName>
        <Authors>B.Verboven</Authors>
        <Company>Regira</Company>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
	    <PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.11" />
        <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Regira.DAL.EFcore" Version="4.9.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fleet.Identity.Models\Fleet.Identity.Models.csproj" />
    </ItemGroup>

</Project>
