<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
      <RootNamespace>Regira.Fleet.Authentication</RootNamespace>
      <AssemblyName>Regira.Fleet.Authentication</AssemblyName>
      <Authors>B.Verboven</Authors>
      <Company>Regira</Company>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Regira.Security.Authentication" Version="4.0.4" />
    </ItemGroup>

</Project>
