// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Regira.Fleet.Data;

#nullable disable

namespace Regira.Fleet.Migrations
{
    [DbContext(typeof(FleetContext))]
    [Migration("20240403133008_InitialStatisticsViews")]
    partial class InitialStatisticsViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Regira.Entities.Attachments.Models.Attachment<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.Property<string>("Path")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("path");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionOperators.Addresses.OperatorAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Box")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("box");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("NormalizedContent")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_content");

                    b.Property<string>("Number")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("number");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    b.Property<string>("PostBox")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("post_box");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("postal_code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Street")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("street");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_intervention_operator_addresses");

                    b.HasIndex("NormalizedContent")
                        .HasDatabaseName("ix_intervention_operator_addresses_normalized_content");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("ix_intervention_operator_addresses_operator_id");

                    b.ToTable("intervention_operator_addresses", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionOperators.ContactData.OperatorContactData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("NormalizedValue")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_value");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_intervention_operator_contactdata");

                    b.HasIndex("NormalizedValue")
                        .HasDatabaseName("ix_intervention_operator_contactdata_normalized_value");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("ix_intervention_operator_contactdata_operator_id");

                    b.ToTable("intervention_operator_contactdata", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionOperators.Operators.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("guid");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identification_number");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("NormalizedContent")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_content");

                    b.Property<string>("NormalizedIdentificationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_identification_number");

                    b.Property<string>("NormalizedTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_intervention_operators");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_intervention_operators_client_id");

                    b.HasIndex("NormalizedTitle")
                        .HasDatabaseName("ix_intervention_operators_normalized_title");

                    b.HasIndex("ClientId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_intervention_operators_client_id_code");

                    b.ToTable("intervention_operators", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionOperators.Operators.OperatorAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttachmentId")
                        .HasColumnType("integer")
                        .HasColumnName("attachment_id");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("object_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_intervention_operator_attachments");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_intervention_operator_attachments_attachment_id");

                    b.HasIndex("ObjectId")
                        .HasDatabaseName("ix_intervention_operator_attachments_object_id");

                    b.ToTable("intervention_operator_attachments", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionOperators.Operators.OperatorInterventionType", b =>
                {
                    b.Property<int>("OperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    b.Property<int>("InterventionTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_type_id");

                    b.HasKey("OperatorId", "InterventionTypeId")
                        .HasName("pk_intervention_operator_intervention_types");

                    b.HasIndex("InterventionTypeId")
                        .HasDatabaseName("ix_intervention_operator_intervention_types_intervention_type_");

                    b.ToTable("intervention_operator_intervention_types", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionTypes.InterventionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("guid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("NormalizedTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_intervention_types");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_intervention_types_client_id");

                    b.HasIndex("NormalizedTitle")
                        .HasDatabaseName("ix_intervention_types_normalized_title");

                    b.HasIndex("ClientId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_intervention_types_client_id_code");

                    b.HasIndex("ClientId", "Title")
                        .IsUnique()
                        .HasDatabaseName("ix_intervention_types_client_id_title");

                    b.ToTable("intervention_types", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionTypes.InterventionTypeTranslation", b =>
                {
                    b.Property<int>("InterventionTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_type_id");

                    b.Property<string>("LangCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("lang_code");

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<string>("NormalizedTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("InterventionTypeId", "LangCode")
                        .HasName("pk_intervention_type_translations");

                    b.ToTable("intervention_type_translations", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Interventions.Action.InterventionAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("guid");

                    b.Property<int?>("InterventionId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_id");

                    b.Property<int?>("InterventionTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_type_id");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("NormalizedContent")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_content");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_intervention_actions");

                    b.HasIndex("InterventionId")
                        .HasDatabaseName("ix_intervention_actions_intervention_id");

                    b.HasIndex("InterventionTypeId")
                        .HasDatabaseName("ix_intervention_actions_intervention_type_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_intervention_actions_invoice_id");

                    b.ToTable("intervention_actions", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Interventions.Action.InterventionActionAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttachmentId")
                        .HasColumnType("integer")
                        .HasColumnName("attachment_id");

                    b.Property<int?>("InterventionActionId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_action_id");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("object_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_intervention_action_attachment");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_intervention_action_attachment_attachment_id");

                    b.HasIndex("InterventionActionId")
                        .HasDatabaseName("ix_intervention_action_attachment_intervention_action_id");

                    b.ToTable("intervention_action_attachment", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Interventions.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("guid");

                    b.Property<DateTime?>("InterventionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("intervention_date");

                    b.Property<int?>("InterventionTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_type_id");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("NormalizedContent")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_content");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_interventions");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_interventions_client_id");

                    b.HasIndex("InterventionTypeId")
                        .HasDatabaseName("ix_interventions_intervention_type_id");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("ix_interventions_operator_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_interventions_vehicle_id");

                    b.ToTable("interventions", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Interventions.InterventionAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttachmentId")
                        .HasColumnType("integer")
                        .HasColumnName("attachment_id");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("object_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_intervention_attachments");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_intervention_attachments_attachment_id");

                    b.HasIndex("ObjectId")
                        .HasDatabaseName("ix_intervention_attachments_object_id");

                    b.ToTable("intervention_attachments", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Interventions.Invoices.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("InterventionId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_id");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("invoice_number");

                    b.Property<decimal?>("PriceExcl")
                        .HasColumnType("decimal(9, 2)")
                        .HasColumnName("price_excl");

                    b.Property<decimal?>("PriceIncl")
                        .HasColumnType("decimal(9, 2)")
                        .HasColumnName("price_incl");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(9, 2)")
                        .HasColumnName("tax_amount");

                    b.Property<int?>("TaxCategory")
                        .HasColumnType("integer")
                        .HasColumnName("tax_category");

                    b.HasKey("Id")
                        .HasName("pk_intervention_invoices");

                    b.HasIndex("InterventionId")
                        .IsUnique()
                        .HasDatabaseName("ix_intervention_invoices_intervention_id");

                    b.HasIndex("InvoiceNumber")
                        .HasDatabaseName("ix_intervention_invoices_invoice_number");

                    b.ToTable("intervention_invoices", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.Brands.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("guid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("NormalizedTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_brands");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_vehicle_brands_client_id");

                    b.HasIndex("NormalizedTitle")
                        .HasDatabaseName("ix_vehicle_brands_normalized_title");

                    b.HasIndex("ClientId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_brands_client_id_code");

                    b.HasIndex("ClientId", "Title")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_brands_client_id_title");

                    b.ToTable("vehicle_brands", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.Brands.BrandTranslation", b =>
                {
                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<string>("LangCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("lang_code");

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<string>("NormalizedTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("BrandId", "LangCode")
                        .HasName("pk_vehicle_brand_translations");

                    b.ToTable("vehicle_brand_translations", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("guid");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identification_number");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<string>("NormalizedContent")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_content");

                    b.Property<string>("NormalizedIdentificationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_identification_number");

                    b.Property<string>("NormalizedTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_title");

                    b.Property<int?>("VehicleTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_type_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_vehicles_brand_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_vehicles_client_id");

                    b.HasIndex("NormalizedTitle")
                        .HasDatabaseName("ix_vehicles_normalized_title");

                    b.HasIndex("VehicleTypeId")
                        .HasDatabaseName("ix_vehicles_vehicle_type_id");

                    b.HasIndex("ClientId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_client_id_code");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.VehicleAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttachmentId")
                        .HasColumnType("integer")
                        .HasColumnName("attachment_id");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("object_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_attachments");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_vehicle_attachments_attachment_id");

                    b.HasIndex("ObjectId")
                        .HasDatabaseName("ix_vehicle_attachments_object_id");

                    b.ToTable("vehicle_attachments", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.VehicleInterventionType", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("InterventionTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_type_id");

                    b.HasKey("VehicleId", "InterventionTypeId")
                        .HasName("pk_vehicle_intervention_types");

                    b.HasIndex("InterventionTypeId")
                        .HasDatabaseName("ix_vehicle_intervention_types_intervention_type_id");

                    b.ToTable("vehicle_intervention_types", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.VehicleTypes.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("guid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("NormalizedTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_types");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_vehicle_types_client_id");

                    b.HasIndex("NormalizedTitle")
                        .HasDatabaseName("ix_vehicle_types_normalized_title");

                    b.HasIndex("ClientId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_types_client_id_code");

                    b.HasIndex("ClientId", "Title")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_types_client_id_title");

                    b.ToTable("vehicle_types", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.VehicleTypes.VehicleTypeTranslation", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_type_id");

                    b.Property<string>("LangCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("lang_code");

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<string>("NormalizedTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("VehicleTypeId", "LangCode")
                        .HasName("pk_vehicle_type_translations");

                    b.ToTable("vehicle_type_translations", (string)null);
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionOperators.Addresses.OperatorAddress", b =>
                {
                    b.HasOne("Regira.Fleet.Entities.InterventionOperators.Operators.Operator", null)
                        .WithMany("Addresses")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_operator_addresses_intervention_operators_oper");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionOperators.ContactData.OperatorContactData", b =>
                {
                    b.HasOne("Regira.Fleet.Entities.InterventionOperators.Operators.Operator", null)
                        .WithMany("ContactData")
                        .HasForeignKey("OperatorId")
                        .HasConstraintName("fk_intervention_operator_contactdata_intervention_operators_op");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionOperators.Operators.OperatorAttachment", b =>
                {
                    b.HasOne("Regira.Entities.Attachments.Models.Attachment<int>", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_operator_attachments_attachments_attachment_id");

                    b.HasOne("Regira.Fleet.Entities.InterventionOperators.Operators.Operator", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_operator_attachments_intervention_operators_ob");

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionOperators.Operators.OperatorInterventionType", b =>
                {
                    b.HasOne("Regira.Fleet.Entities.InterventionTypes.InterventionType", "InterventionType")
                        .WithMany()
                        .HasForeignKey("InterventionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_operator_intervention_types_intervention_types");

                    b.HasOne("Regira.Fleet.Entities.InterventionOperators.Operators.Operator", "Operator")
                        .WithMany("InterventionTypes")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_operator_intervention_types_intervention_opera");

                    b.Navigation("InterventionType");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionTypes.InterventionTypeTranslation", b =>
                {
                    b.HasOne("Regira.Fleet.Entities.InterventionTypes.InterventionType", null)
                        .WithMany("Translations")
                        .HasForeignKey("InterventionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_type_translations_intervention_types_intervent");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Interventions.Action.InterventionAction", b =>
                {
                    b.HasOne("Regira.Fleet.Entities.Interventions.Intervention", null)
                        .WithMany("Actions")
                        .HasForeignKey("InterventionId")
                        .HasConstraintName("fk_intervention_actions_interventions_intervention_id");

                    b.HasOne("Regira.Fleet.Entities.InterventionTypes.InterventionType", "InterventionType")
                        .WithMany()
                        .HasForeignKey("InterventionTypeId")
                        .HasConstraintName("fk_intervention_actions_intervention_types_intervention_type_id");

                    b.HasOne("Regira.Fleet.Entities.Interventions.Invoices.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_actions_invoice_invoice_id");

                    b.Navigation("InterventionType");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Interventions.Action.InterventionActionAttachment", b =>
                {
                    b.HasOne("Regira.Entities.Attachments.Models.Attachment<int>", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_action_attachment_attachments_attachment_id");

                    b.HasOne("Regira.Fleet.Entities.Interventions.Action.InterventionAction", null)
                        .WithMany("Attachments")
                        .HasForeignKey("InterventionActionId")
                        .HasConstraintName("fk_intervention_action_attachment_intervention_actions_interve");

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Interventions.Intervention", b =>
                {
                    b.HasOne("Regira.Fleet.Entities.InterventionTypes.InterventionType", "InterventionType")
                        .WithMany()
                        .HasForeignKey("InterventionTypeId")
                        .HasConstraintName("fk_interventions_intervention_types_intervention_type_id");

                    b.HasOne("Regira.Fleet.Entities.InterventionOperators.Operators.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interventions_intervention_operators_operator_id");

                    b.HasOne("Regira.Fleet.Entities.Vehicles.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interventions_vehicles_vehicle_id");

                    b.Navigation("InterventionType");

                    b.Navigation("Operator");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Interventions.InterventionAttachment", b =>
                {
                    b.HasOne("Regira.Entities.Attachments.Models.Attachment<int>", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_attachments_attachments_attachment_id");

                    b.HasOne("Regira.Fleet.Entities.Interventions.Intervention", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_attachments_interventions_object_id");

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Interventions.Invoices.Invoice", b =>
                {
                    b.HasOne("Regira.Fleet.Entities.Interventions.Intervention", null)
                        .WithOne("Invoice")
                        .HasForeignKey("Regira.Fleet.Entities.Interventions.Invoices.Invoice", "InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_invoices_interventions_intervention_id");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.Brands.BrandTranslation", b =>
                {
                    b.HasOne("Regira.Fleet.Entities.Vehicles.Brands.Brand", null)
                        .WithMany("Translations")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_brand_translations_vehicle_brands_brand_id");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.Vehicle", b =>
                {
                    b.HasOne("Regira.Fleet.Entities.Vehicles.Brands.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .HasConstraintName("fk_vehicles_brands_brand_id");

                    b.HasOne("Regira.Fleet.Entities.Vehicles.VehicleTypes.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .HasConstraintName("fk_vehicles_vehicle_types_vehicle_type_id");

                    b.Navigation("Brand");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.VehicleAttachment", b =>
                {
                    b.HasOne("Regira.Entities.Attachments.Models.Attachment<int>", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_attachments_attachments_attachment_id");

                    b.HasOne("Regira.Fleet.Entities.Vehicles.Vehicle", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_attachments_vehicles_object_id");

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.VehicleInterventionType", b =>
                {
                    b.HasOne("Regira.Fleet.Entities.InterventionTypes.InterventionType", "InterventionType")
                        .WithMany()
                        .HasForeignKey("InterventionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_intervention_types_intervention_types_intervention_");

                    b.HasOne("Regira.Fleet.Entities.Vehicles.Vehicle", "Vehicle")
                        .WithMany("InterventionTypes")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_intervention_types_vehicles_vehicle_id");

                    b.Navigation("InterventionType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.VehicleTypes.VehicleTypeTranslation", b =>
                {
                    b.HasOne("Regira.Fleet.Entities.Vehicles.VehicleTypes.VehicleType", null)
                        .WithMany("Translations")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_type_translations_vehicle_types_vehicle_type_id");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionOperators.Operators.Operator", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Attachments");

                    b.Navigation("ContactData");

                    b.Navigation("InterventionTypes");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.InterventionTypes.InterventionType", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Interventions.Action.InterventionAction", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Interventions.Intervention", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Attachments");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.Brands.Brand", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.Vehicle", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("InterventionTypes");
                });

            modelBuilder.Entity("Regira.Fleet.Entities.Vehicles.VehicleTypes.VehicleType", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
