// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Regira.Fleet.Data;

namespace Regira.Fleet.Aca.Library.Migrations
{
    [DbContext(typeof(FleetContext))]
    partial class FleetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Regira.Fleet.Aca.Library.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<int?>("CarId")
                        .HasColumnName("car_id")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnName("comments")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Hyperlink")
                        .HasColumnName("hyperlink")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<int?>("InterventionTypeId")
                        .HasColumnName("intervention_type_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnName("invoice_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnName("invoice_number")
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.Property<DateTime>("LastModified")
                        .HasColumnName("last_modified")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Mileage")
                        .HasColumnName("mileage")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnName("notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal?>("PriceExcl")
                        .HasColumnName("price_excl")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<decimal?>("PriceIncl")
                        .HasColumnName("price_incl")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<int?>("SupplierId")
                        .HasColumnName("supplier_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnName("tax_amount")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<string>("TaxCategory")
                        .HasColumnName("tax_category")
                        .HasColumnType("varchar(1) CHARACTER SET utf8mb4")
                        .HasMaxLength(1);

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CarId")
                        .HasName("ix_bookings_car_id");

                    b.HasIndex("InterventionTypeId")
                        .HasName("ix_bookings_intervention_type_id");

                    b.HasIndex("InvoiceDate")
                        .HasName("ix_bookings_invoice_date");

                    b.HasIndex("InvoiceNumber")
                        .HasName("ix_bookings_invoice_number");

                    b.HasIndex("SupplierId")
                        .HasName("ix_bookings_supplier_id");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("Regira.Fleet.Aca.Library.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("varchar(3) CHARACTER SET utf8mb4")
                        .HasMaxLength(3);

                    b.Property<bool>("IsArchived")
                        .HasColumnName("is_archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("ix_brands_code");

                    b.HasIndex("Title")
                        .HasName("ix_brands_title");

                    b.ToTable("brands");
                });

            modelBuilder.Entity("Regira.Fleet.Aca.Library.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<int?>("BrandId")
                        .HasColumnName("brand_id")
                        .HasColumnType("int");

                    b.Property<int?>("CarTypeId")
                        .HasColumnName("car_type_id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("varchar(8) CHARACTER SET utf8mb4")
                        .HasMaxLength(8);

                    b.Property<bool>("IsArchived")
                        .HasColumnName("is_archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Model")
                        .HasColumnName("model")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.HasKey("Id")
                        .HasName("pk_cars");

                    b.HasIndex("BrandId")
                        .HasName("ix_cars_brand_id");

                    b.HasIndex("CarTypeId")
                        .HasName("ix_cars_car_type_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("ix_cars_code");

                    b.ToTable("cars");
                });

            modelBuilder.Entity("Regira.Fleet.Aca.Library.Entities.CarType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("varchar(3) CHARACTER SET utf8mb4")
                        .HasMaxLength(3);

                    b.Property<bool>("IsArchived")
                        .HasColumnName("is_archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.HasKey("Id")
                        .HasName("pk_car_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("ix_car_types_code");

                    b.HasIndex("Title")
                        .HasName("ix_car_types_title");

                    b.ToTable("car_types");
                });

            modelBuilder.Entity("Regira.Fleet.Aca.Library.Entities.InterventionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("varchar(3) CHARACTER SET utf8mb4")
                        .HasMaxLength(3);

                    b.Property<bool>("IsArchived")
                        .HasColumnName("is_archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.HasKey("Id")
                        .HasName("pk_intervention_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("ix_intervention_types_code");

                    b.HasIndex("Title")
                        .HasName("ix_intervention_types_title");

                    b.ToTable("intervention_types");
                });

            modelBuilder.Entity("Regira.Fleet.Aca.Library.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Address1")
                        .HasColumnName("address1")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("Address2")
                        .HasColumnName("address2")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<string>("CountryCode")
                        .HasColumnName("country_code")
                        .HasColumnType("varchar(2) CHARACTER SET utf8mb4")
                        .HasMaxLength(2);

                    b.Property<DateTime?>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<bool>("IsArchived")
                        .HasColumnName("is_archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnName("last_modified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .HasColumnName("location")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("Name2")
                        .HasColumnName("name2")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("Notes")
                        .HasColumnName("notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Phone1")
                        .HasColumnName("phone1")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<string>("Phone2")
                        .HasColumnName("phone2")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<string>("PostalCode")
                        .HasColumnName("postal_code")
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.Property<int?>("SupplierTypeId")
                        .HasColumnName("supplier_type_id")
                        .HasColumnType("int");

                    b.Property<string>("VATNumber")
                        .HasColumnName("vat_number")
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("ix_suppliers_code");

                    b.HasIndex("Name")
                        .HasName("ix_suppliers_name");

                    b.HasIndex("SupplierTypeId")
                        .HasName("ix_suppliers_supplier_type_id");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("Regira.Fleet.Aca.Library.Entities.SupplierType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("varchar(3) CHARACTER SET utf8mb4")
                        .HasMaxLength(3);

                    b.Property<bool>("IsArchived")
                        .HasColumnName("is_archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.HasKey("Id")
                        .HasName("pk_supplier_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("ix_supplier_types_code");

                    b.HasIndex("Title")
                        .HasName("ix_supplier_types_title");

                    b.ToTable("supplier_types");
                });

            modelBuilder.Entity("Regira.Fleet.Aca.Library.Entities.Booking", b =>
                {
                    b.HasOne("Regira.Fleet.Aca.Library.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .HasConstraintName("fk_bookings_cars_car_id");

                    b.HasOne("Regira.Fleet.Aca.Library.Entities.InterventionType", "InterventionType")
                        .WithMany()
                        .HasForeignKey("InterventionTypeId")
                        .HasConstraintName("fk_bookings_intervention_types_intervention_type_id");

                    b.HasOne("Regira.Fleet.Aca.Library.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("fk_bookings_suppliers_supplier_id");
                });

            modelBuilder.Entity("Regira.Fleet.Aca.Library.Entities.Car", b =>
                {
                    b.HasOne("Regira.Fleet.Aca.Library.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .HasConstraintName("fk_cars_brands_brand_id");

                    b.HasOne("Regira.Fleet.Aca.Library.Entities.CarType", "CarType")
                        .WithMany()
                        .HasForeignKey("CarTypeId")
                        .HasConstraintName("fk_cars_car_types_car_type_id");
                });

            modelBuilder.Entity("Regira.Fleet.Aca.Library.Entities.Supplier", b =>
                {
                    b.HasOne("Regira.Fleet.Aca.Library.Entities.SupplierType", "SupplierType")
                        .WithMany()
                        .HasForeignKey("SupplierTypeId")
                        .HasConstraintName("fk_suppliers_supplier_types_supplier_type_id");
                });
#pragma warning restore 612, 618
        }
    }
}
